CONST = {
    'Chicago': {
        'IGNORE_FEATURES': [
            'CRASH_RECORD_ID',
            'RD_NO',
            'REPORT_TYPE',
            'HIT_AND_RUN_I',
            'DAMAGE',
            'DATE_POLICE_NOTIFIED',
            'SEC_CONTRIBUTORY_CAUSE',
            'STREET_NAME',
            'STREET_NO',
            'BEAT_OF_OCCURRENCE',
            'PHOTOS_TAKEN_I',
            'STATEMENTS_TAKEN_I',
            'LATITUDE',
            'LONGITUDE',
            'LOCATION',
            'CRASH_DATE_EST_I',
            'CRASH_DATE',
            'CRASH_MONTH',
            'LANE_CNT',
            'MOST_SEVERE_INJURY',
            'INJURIES_TOTAL',
            'INJURIES_REPORTED_NOT_EVIDENT',
            'INJURIES_NO_INDICATION', 
            'INJURIES_UNKNOWN', 
            'CRASH_TYPE',
        ],
        'DATA_TYPES': {
            'POSTED_SPEED_LIMIT': object,
            'TRAFFIC_CONTROL_DEVICE': str,
            'DEVICE_CONDITION': str,
            'WEATHER_CONDITION': str,
            'LIGHTING_CONDITION': str,
            'FIRST_CRASH_TYPE': str,
            'TRAFFICWAY_TYPE': str,
            'ALIGNMENT': str,
            'ROADWAY_SURFACE_COND': str,
            'ROAD_DEFECT': str,
            'INTERSECTION_RELATED_I': str,
            'NOT_RIGHT_OF_WAY_I': str,
            'PRIM_CONTRIBUTORY_CAUSE': str,
            'STREET_DIRECTION': str,
            'DOORING_I': str,
            'WORK_ZONE_I': str,
            'NUM_UNITS': object,
            'INJURIES_FATAL': object,
            'INJURIES_INCAPACITATING': object,
            'INJURIES_NON_INCAPACITATING': object,
            'CRASH_HOUR': object,
            'CRASH_DAY_OF_WEEK': str,
        },
        'FEATURES_REMOVED_POST_CLEAN': [
            'WORK_ZONE_TYPE',
            'WORKERS_PRESENT_I'
        ]
        ,
        'DAY_OF_WEEK': {
            'Monday': 2,
            'Tuesday': 3,
            'Wednesday': 4,
            'Thursday': 5,
            'Friday': 6,
            'Saturday': 7,
            'Sunday': 1
        }, 
        'MIN_PAGE': 1,
        'NUM_PAGE': 8,
    }
}